const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('drakoria', {
  getVersion: () => ipcRenderer.invoke('app:version'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (settings) => ipcRenderer.invoke('settings:save', settings),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  getUpdateHistory: () => ipcRenderer.invoke('updates:history'),
  openPreviousVersions: () => ipcRenderer.invoke('updates:open-releases'),
  exportBackup: (password = '') => ipcRenderer.invoke('backup:export', password),
  importBackup: (password = '') => ipcRenderer.invoke('backup:import', password),
  onUpdateStatus: (callback) => ipcRenderer.on('updates:status', (_event, status) => callback(status)),
  onNavigationBlocked: (callback) => ipcRenderer.on('navigation:blocked', (_event, value) => callback(value)),
  listGames: () => ipcRenderer.invoke('games:list'),
  listGroups: () => ipcRenderer.invoke('groups:list'),
  saveGroup: (group) => ipcRenderer.invoke('groups:save', group),
  deleteGroup: (id) => ipcRenderer.invoke('groups:delete', id),
  listEvents: (gameId = '') => ipcRenderer.invoke('events:list', gameId),
  getMonitor: (gameId) => ipcRenderer.invoke('monitors:get', gameId),
  saveMonitor: (gameId, monitor) => ipcRenderer.invoke('monitors:save', gameId, monitor),
  getCredentials: (id) => ipcRenderer.invoke('games:credentials', id),
  saveGame: (game) => ipcRenderer.invoke('games:save', game),
  deleteGame: (id, clearSession = false) => ipcRenderer.invoke('games:delete', id, clearSession),
  getDiagnostics: () => ipcRenderer.invoke('games:diagnostics'),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  listReminders: () => ipcRenderer.invoke('reminders:list'),
  saveReminder: (reminder) => ipcRenderer.invoke('reminders:save', reminder),
  deleteReminder: (id) => ipcRenderer.invoke('reminders:delete', id),
  onRemindersChanged: (callback) => ipcRenderer.on('reminders:changed', callback),
  getNote: (gameId) => ipcRenderer.invoke('notes:get', gameId),
  saveNote: (gameId, value) => ipcRenderer.invoke('notes:save', gameId, value),
  getCompanion: (gameId) => ipcRenderer.invoke('companion:get', gameId),
  saveCompanion: (gameId, value) => ipcRenderer.invoke('companion:save', gameId, value)
});
